[server]
address = "127.0.0.1"
headless = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#17766e"
backgroundColor = "#fbfcfa"
secondaryBackgroundColor = "#eef3ef"
textColor = "#223a3d"
font = "sans serif"
